#!/bin/bash

if [ "$1" == "asm" ]; then
    gcc asm/asm.c -Wall -Wextra
    ./a.out $2 
    rm a.out
elif [ "$1" == "emu" ]; then
    gcc emu/emu.c -Wall -Wextra -lraylib
    ./a.out $2 
    rm a.out
else 
    echo "ded"
fi
