#!/bin/bash

if [ "$1" == "pipe" ]; then
    gcc asm/asm.c -Wall -Wextra -fsanitize=address -g
    ./a.out $2 
    rm a.out
    gcc emu/emu.c -Wall -Wextra -lraylib
    ./a.out out.bin
    rm a.out
    rm out.bin
elif [ "$1" == "asm" ]; then
    gcc asm/asm.c -Wall -Wextra -fsanitize=address -g
    ./a.out $2 
    rm a.out
elif [ "$1" == "emu" ]; then
    gcc emu/emu.c -Wall -Wextra -lraylib
    ./a.out $2 
    rm a.out
else 
    echo "ded"
fi
