#!/bin/bash

if [ "$1" == "asm" ]; then
    gcc asm/asm.c -Wall -Wextra -std=c99 -Og 
    ./a.out $2 
    rm a.out
elif [ "$1" == "emu" ]; then
    gcc emu/emu.c -Wall -Wextra -std=c99 -Og 
    ./a.out $2 
    rm a.out
fi
